//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutPageConstants {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutPageConstants() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.AboutPageConstants", typeof(AboutPageConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        public static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        public static string Forks {
            get {
                return ResourceManager.GetString("Forks", resourceCulture);
            }
        }
        
        public static string Watching {
            get {
                return ResourceManager.GetString("Watching", resourceCulture);
            }
        }
        
        public static string CollaboratorsTitle {
            get {
                return ResourceManager.GetString("CollaboratorsTitle", resourceCulture);
            }
        }
        
        public static string CollaboratorsDescription {
            get {
                return ResourceManager.GetString("CollaboratorsDescription", resourceCulture);
            }
        }
        
        public static string LibrariesTitle {
            get {
                return ResourceManager.GetString("LibrariesTitle", resourceCulture);
            }
        }
        
        public static string LibrariesDescription {
            get {
                return ResourceManager.GetString("LibrariesDescription", resourceCulture);
            }
        }
        
        public static string GitHubButton {
            get {
                return ResourceManager.GetString("GitHubButton", resourceCulture);
            }
        }
        
        public static string RequestFeatureButton {
            get {
                return ResourceManager.GetString("RequestFeatureButton", resourceCulture);
            }
        }
    }
}
