//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmptyDataViewConstantsInternal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmptyDataViewConstantsInternal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.EmptyDataViewConstantsInternal", typeof(EmptyDataViewConstantsInternal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear search bar and try again.
        /// </summary>
        internal static string ClearSearchBarTryAgain {
            get {
                return ResourceManager.GetString("ClearSearchBarTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve earned your first star.
        /// </summary>
        internal static string FirstStar {
            get {
                return ResourceManager.GetString("FirstStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOADING.
        /// </summary>
        internal static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Login Expired.
        /// </summary>
        internal static string LoginExpired {
            get {
                return ResourceManager.GetString("LoginExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matching Repository Found.
        /// </summary>
        internal static string NoFilterMatch {
            get {
                return ResourceManager.GetString("NoFilterMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No referrals yet.
        /// </summary>
        internal static string NoReferralsYet {
            get {
                return ResourceManager.GetString("NoReferralsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your repositories list is empty.
        /// </summary>
        internal static string NoRepositoriesFound {
            get {
                return ResourceManager.GetString("NoRepositoriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Stars Yet.
        /// </summary>
        internal static string NoStarsYet {
            get {
                return ResourceManager.GetString("NoStarsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No traffic yet.
        /// </summary>
        internal static string NoTrafficYet {
            get {
                return ResourceManager.GetString("NoTrafficYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login again.
        /// </summary>
        internal static string PleaseLoginAgain {
            get {
                return ResourceManager.GetString("PleaseLoginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe down to retrieve referring sites.
        /// </summary>
        internal static string SwipeDownToRefresh_ReferringSites {
            get {
                return ResourceManager.GetString("SwipeDownToRefresh_ReferringSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe down to retrieve repositories.
        /// </summary>
        internal static string SwipeDownToRefresh_Repositories {
            get {
                return ResourceManager.GetString("SwipeDownToRefresh_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        internal static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve data.
        /// </summary>
        internal static string UnableToRetrieveData {
            get {
                return ResourceManager.GetString("UnableToRetrieveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not gathered.
        /// </summary>
        internal static string Uninitialized {
            get {
                return ResourceManager.GetString("Uninitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No worries! Keep up the good work and the stars come!.
        /// </summary>
        internal static string ZeroStarsEmptyDataViewDescription1 {
            get {
                return ResourceManager.GetString("ZeroStarsEmptyDataViewDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite the community to check out your great work!.
        /// </summary>
        internal static string ZeroStarsEmptyDataViewDescription2 {
            get {
                return ResourceManager.GetString("ZeroStarsEmptyDataViewDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share updates with friends and get your first star!.
        /// </summary>
        internal static string ZeroStarsEmptyDataViewDescription3 {
            get {
                return ResourceManager.GetString("ZeroStarsEmptyDataViewDescription3", resourceCulture);
            }
        }
    }
}
