//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmptyDataViewConstantsInternal {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmptyDataViewConstantsInternal() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.EmptyDataViewConstantsInternal", typeof(EmptyDataViewConstantsInternal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PleaseLoginAgain {
            get {
                return ResourceManager.GetString("PleaseLoginAgain", resourceCulture);
            }
        }
        
        public static string SwipeDownToRefresh_Repositories {
            get {
                return ResourceManager.GetString("SwipeDownToRefresh_Repositories", resourceCulture);
            }
        }
        
        public static string SwipeDownToRefresh_ReferringSites {
            get {
                return ResourceManager.GetString("SwipeDownToRefresh_ReferringSites", resourceCulture);
            }
        }
        
        public static string LoginExpired {
            get {
                return ResourceManager.GetString("LoginExpired", resourceCulture);
            }
        }
        
        public static string NoFilterMatch {
            get {
                return ResourceManager.GetString("NoFilterMatch", resourceCulture);
            }
        }
        
        public static string NoRepositoriesFound {
            get {
                return ResourceManager.GetString("NoRepositoriesFound", resourceCulture);
            }
        }
        
        public static string ClearSearchBarTryAgain {
            get {
                return ResourceManager.GetString("ClearSearchBarTryAgain", resourceCulture);
            }
        }
        
        public static string NoReferralsYet {
            get {
                return ResourceManager.GetString("NoReferralsYet", resourceCulture);
            }
        }
        
        public static string Uninitialized {
            get {
                return ResourceManager.GetString("Uninitialized", resourceCulture);
            }
        }
    }
}
