//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmptyDataViewConstantsInternal_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmptyDataViewConstantsInternal_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.EmptyDataViewConstantsInternal-ru", typeof(EmptyDataViewConstantsInternal_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистите поисковую строку и повторите попытку.
        /// </summary>
        internal static string ClearSearchBarTryAgain {
            get {
                return ResourceManager.GetString("ClearSearchBarTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин GitHub истек.
        /// </summary>
        internal static string LoginExpired {
            get {
                return ResourceManager.GetString("LoginExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден подходящий репозиторий.
        /// </summary>
        internal static string NoFilterMatch {
            get {
                return ResourceManager.GetString("NoFilterMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пока нет ссылок.
        /// </summary>
        internal static string NoReferralsYet {
            get {
                return ResourceManager.GetString("NoReferralsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список Ваших репозиториев пуст.
        /// </summary>
        internal static string NoRepositoriesFound {
            get {
                return ResourceManager.GetString("NoRepositoriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, войдите заново.
        /// </summary>
        internal static string PleaseLoginAgain {
            get {
                return ResourceManager.GetString("PleaseLoginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проведите вниз, чтобы получить ссылающиеся сайты.
        /// </summary>
        internal static string SwipeDownToRefresh_ReferringSites {
            get {
                return ResourceManager.GetString("SwipeDownToRefresh_ReferringSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проведите вниз, чтобы получить репозитории.
        /// </summary>
        internal static string SwipeDownToRefresh_Repositories {
            get {
                return ResourceManager.GetString("SwipeDownToRefresh_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные не были собраны.
        /// </summary>
        internal static string Uninitialized {
            get {
                return ResourceManager.GetString("Uninitialized", resourceCulture);
            }
        }
    }
}
