//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationConstants {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationConstants() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.NotificationConstants", typeof(NotificationConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string TrendingRepositoriesNotificationTitle {
            get {
                return ResourceManager.GetString("TrendingRepositoriesNotificationTitle", resourceCulture);
            }
        }
        
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        public static string IsTrending {
            get {
                return ResourceManager.GetString("IsTrending", resourceCulture);
            }
        }
        
        public static string SingleRepositoryNotificationMessage {
            get {
                return ResourceManager.GetString("SingleRepositoryNotificationMessage", resourceCulture);
            }
        }
        
        public static string MultipleRepositoryNotificationMessage {
            get {
                return ResourceManager.GetString("MultipleRepositoryNotificationMessage", resourceCulture);
            }
        }
        
        public static string NotificationsDisabled {
            get {
                return ResourceManager.GetString("NotificationsDisabled", resourceCulture);
            }
        }
        
        public static string NotificationsNotSupported {
            get {
                return ResourceManager.GetString("NotificationsNotSupported", resourceCulture);
            }
        }
        
        public static string HandleNotification_SingleTrendingRepository_Title {
            get {
                return ResourceManager.GetString("HandleNotification_SingleTrendingRepository_Title", resourceCulture);
            }
        }
        
        public static string HandleNotification_SingleTrendingRepository_Message {
            get {
                return ResourceManager.GetString("HandleNotification_SingleTrendingRepository_Message", resourceCulture);
            }
        }
        
        public static string HandleNotification_SingleTrendingRepository_Accept {
            get {
                return ResourceManager.GetString("HandleNotification_SingleTrendingRepository_Accept", resourceCulture);
            }
        }
        
        public static string HandleNotification_SingleTrendingRepository_Decline {
            get {
                return ResourceManager.GetString("HandleNotification_SingleTrendingRepository_Decline", resourceCulture);
            }
        }
        
        public static string HandleNotification_MultipleTrendingRepository_Sorted_Message {
            get {
                return ResourceManager.GetString("HandleNotification_MultipleTrendingRepository_Sorted_Message", resourceCulture);
            }
        }
        
        public static string HandleNotification_MultipleTrendingRepository_Cancel {
            get {
                return ResourceManager.GetString("HandleNotification_MultipleTrendingRepository_Cancel", resourceCulture);
            }
        }
        
        public static string HandleNotification_MultipleTrendingRepositor_Unsorted_Message {
            get {
                return ResourceManager.GetString("HandleNotification_MultipleTrendingRepositor_Unsorted_Message", resourceCulture);
            }
        }
        
        public static string HandleNotification_MultipleTrendingRepositor_Unsorted_Accept {
            get {
                return ResourceManager.GetString("HandleNotification_MultipleTrendingRepositor_Unsorted_Accept", resourceCulture);
            }
        }
        
        public static string HandleNotification_MultipleTrendingRepositor_Unsorted_Decline {
            get {
                return ResourceManager.GetString("HandleNotification_MultipleTrendingRepositor_Unsorted_Decline", resourceCulture);
            }
        }
    }
}
