//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationConstants_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationConstants_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.NotificationConstants-ru", typeof(NotificationConstants_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратная Сортировка.
        /// </summary>
        public static string HandleNotification_MultipleTrendingRepositor_Unsorted_Accept {
            get {
                return ResourceManager.GetString("HandleNotification_MultipleTrendingRepositor_Unsorted_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не Сейчас.
        /// </summary>
        public static string HandleNotification_MultipleTrendingRepositor_Unsorted_Decline {
            get {
                return ResourceManager.GetString("HandleNotification_MultipleTrendingRepositor_Unsorted_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратить Сортировку, Чтобы Понять Какие.
        /// </summary>
        public static string HandleNotification_MultipleTrendingRepositor_Unsorted_Message {
            get {
                return ResourceManager.GetString("HandleNotification_MultipleTrendingRepositor_Unsorted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо.
        /// </summary>
        public static string HandleNotification_MultipleTrendingRepository_Cancel {
            get {
                return ResourceManager.GetString("HandleNotification_MultipleTrendingRepository_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите на репозитории с пометкой &quot;В Тренде&quot; чтобы увидеть подробности!.
        /// </summary>
        public static string HandleNotification_MultipleTrendingRepository_Sorted_Message {
            get {
                return ResourceManager.GetString("HandleNotification_MultipleTrendingRepository_Sorted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поехали.
        /// </summary>
        public static string HandleNotification_SingleTrendingRepository_Accept {
            get {
                return ResourceManager.GetString("HandleNotification_SingleTrendingRepository_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не Прямо Сейчас.
        /// </summary>
        public static string HandleNotification_SingleTrendingRepository_Decline {
            get {
                return ResourceManager.GetString("HandleNotification_SingleTrendingRepository_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давайте Проверим Эту Диаграмму.
        /// </summary>
        public static string HandleNotification_SingleTrendingRepository_Message {
            get {
                return ResourceManager.GetString("HandleNotification_SingleTrendingRepository_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} в Тренде.
        /// </summary>
        public static string HandleNotification_SingleTrendingRepository_Title {
            get {
                return ResourceManager.GetString("HandleNotification_SingleTrendingRepository_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в Тренде.
        /// </summary>
        public static string IsTrending {
            get {
                return ResourceManager.GetString("IsTrending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас есть {0} Репозиториев Находящихся в Тренде.
        /// </summary>
        public static string MultipleRepositoryNotificationMessage {
            get {
                return ResourceManager.GetString("MultipleRepositoryNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оповещения Отключены.
        /// </summary>
        public static string NotificationsDisabled {
            get {
                return ResourceManager.GetString("NotificationsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оповещения не Поддерживаются.
        /// </summary>
        public static string NotificationsNotSupported {
            get {
                return ResourceManager.GetString("NotificationsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} созданный {1} в тренде.
        /// </summary>
        public static string SingleRepositoryNotificationMessage {
            get {
                return ResourceManager.GetString("SingleRepositoryNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши Репозитории в Тренде.
        /// </summary>
        public static string TrendingRepositoriesNotificationTitle {
            get {
                return ResourceManager.GetString("TrendingRepositoriesNotificationTitle", resourceCulture);
            }
        }
    }
}
