//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OnboardingConstants_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnboardingConstants_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.OnboardingConstants-ru", typeof(OnboardingConstants_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долгое нажатие на график позволит увидеть точные численные значения.
        /// </summary>
        public static string ChartPage_Body_LongPress {
            get {
                return ResourceManager.GetString("ChartPage_Body_LongPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График показывают весь трафик относящийся к Вашему репозиторию:.
        /// </summary>
        public static string ChartPage_Body_ShowAllTraffic {
            get {
                return ResourceManager.GetString("ChartPage_Body_ShowAllTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приблизьте или отдалите чтобы увидеть то, что Вас интересует.
        /// </summary>
        public static string ChartPage_Body_ZoomInOut {
            get {
                return ResourceManager.GetString("ChartPage_Body_ZoomInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получите общее представление о.
        /// </summary>
        public static string ChartPage_Title {
            get {
                return ResourceManager.GetString("ChartPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начните с подключения своей учетной записи GitHub, или попробуйте демонстрационный режим для ознакомления с GitTrends!.
        /// </summary>
        public static string ConnectToGitHubPage_Body_GetStarted {
            get {
                return ResourceManager.GetString("ConnectToGitHubPage_Body_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключитесь к.
        /// </summary>
        public static string ConnectToGitHubPage_Title {
            get {
                return ResourceManager.GetString("ConnectToGitHubPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдите ссылающиеся сайты.
        /// </summary>
        public static string GitTrendsPage_Body_DiscoverReferringSites {
            get {
                return ResourceManager.GetString("GitTrendsPage_Body_DiscoverReferringSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitTrends помогает мониторить GitHub репозитории:.
        /// </summary>
        public static string GitTrendsPage_Body_GitTrendsHelps {
            get {
                return ResourceManager.GetString("GitTrendsPage_Body_GitTrendsHelps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следите за Github Репо Просмотрами, Клонами, Ветками, Звездами и Проблемами.
        /// </summary>
        public static string GitTrendsPage_Body_MonitorGitHubRepos {
            get {
                return ResourceManager.GetString("GitTrendsPage_Body_MonitorGitHubRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в.
        /// </summary>
        public static string GitTrendsPage_Title {
            get {
                return ResourceManager.GetString("GitTrendsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitTrends оповестит Вас, когда Ваши GitHub репозитории используются больше, чем обычно..
        /// </summary>
        public static string NotificationsPage_Body_MoreTrafficThanUsual {
            get {
                return ResourceManager.GetString("NotificationsPage_Body_MoreTrafficThanUsual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получите оповещение, когда .
        /// </summary>
        public static string NotificationsPage_Title {
            get {
                return ResourceManager.GetString("NotificationsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРОПУСТИТЬ.
        /// </summary>
        public static string SkipText {
            get {
                return ResourceManager.GetString("SkipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОПРОБУЙ ДЕМО.
        /// </summary>
        public static string TryDemoText {
            get {
                return ResourceManager.GetString("TryDemoText", resourceCulture);
            }
        }
    }
}
