//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OnboardingConstants {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnboardingConstants() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.OnboardingConstants", typeof(OnboardingConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SkipText {
            get {
                return ResourceManager.GetString("SkipText", resourceCulture);
            }
        }
        
        public static string TryDemoText {
            get {
                return ResourceManager.GetString("TryDemoText", resourceCulture);
            }
        }
        
        public static string ChartPage_Title {
            get {
                return ResourceManager.GetString("ChartPage_Title", resourceCulture);
            }
        }
        
        public static string ChartPage_Body_ShowAllTraffic {
            get {
                return ResourceManager.GetString("ChartPage_Body_ShowAllTraffic", resourceCulture);
            }
        }
        
        public static string ChartPage_Body_ZoomInOut {
            get {
                return ResourceManager.GetString("ChartPage_Body_ZoomInOut", resourceCulture);
            }
        }
        
        public static string ChartPage_Body_LongPress {
            get {
                return ResourceManager.GetString("ChartPage_Body_LongPress", resourceCulture);
            }
        }
        
        public static string ConnectToGitHubPage_Title {
            get {
                return ResourceManager.GetString("ConnectToGitHubPage_Title", resourceCulture);
            }
        }
        
        public static string ConnectToGitHubPage_Body_GetStarted {
            get {
                return ResourceManager.GetString("ConnectToGitHubPage_Body_GetStarted", resourceCulture);
            }
        }
        
        public static string GitTrendsPage_Title {
            get {
                return ResourceManager.GetString("GitTrendsPage_Title", resourceCulture);
            }
        }
        
        public static string GitTrendsPage_Body_GitTrendsHelps {
            get {
                return ResourceManager.GetString("GitTrendsPage_Body_GitTrendsHelps", resourceCulture);
            }
        }
        
        public static string GitTrendsPage_Body_MonitorGitHubRepos {
            get {
                return ResourceManager.GetString("GitTrendsPage_Body_MonitorGitHubRepos", resourceCulture);
            }
        }
        
        public static string GitTrendsPage_Body_DiscoverReferringSites {
            get {
                return ResourceManager.GetString("GitTrendsPage_Body_DiscoverReferringSites", resourceCulture);
            }
        }
        
        public static string NotificationsPage_Title {
            get {
                return ResourceManager.GetString("NotificationsPage_Title", resourceCulture);
            }
        }
        
        public static string NotificationsPage_Body_MoreTrafficThanUsual {
            get {
                return ResourceManager.GetString("NotificationsPage_Body_MoreTrafficThanUsual", resourceCulture);
            }
        }
        
        public static string EnableNotifications {
            get {
                return ResourceManager.GetString("EnableNotifications", resourceCulture);
            }
        }
    }
}
