//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReviewServiceConstants {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReviewServiceConstants() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.ReviewServiceConstants", typeof(ReviewServiceConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string TitleLabel_EnjoyingGitTrends {
            get {
                return ResourceManager.GetString("TitleLabel_EnjoyingGitTrends", resourceCulture);
            }
        }
        
        public static string TitleLabel_EnjoyingNewVersionOfGitTrends {
            get {
                return ResourceManager.GetString("TitleLabel_EnjoyingNewVersionOfGitTrends", resourceCulture);
            }
        }
        
        public static string TitleLabel_Feedback {
            get {
                return ResourceManager.GetString("TitleLabel_Feedback", resourceCulture);
            }
        }
        
        public static string NoButton_NoThanks {
            get {
                return ResourceManager.GetString("NoButton_NoThanks", resourceCulture);
            }
        }
        
        public static string NoButton_NotReally {
            get {
                return ResourceManager.GetString("NoButton_NotReally", resourceCulture);
            }
        }
        
        public static string YesButton_OkSure {
            get {
                return ResourceManager.GetString("YesButton_OkSure", resourceCulture);
            }
        }
        
        public static string YesButton_Yes {
            get {
                return ResourceManager.GetString("YesButton_Yes", resourceCulture);
            }
        }
    }
}
