//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReviewServiceConstants_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReviewServiceConstants_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.ReviewServiceConstants-ru", typeof(ReviewServiceConstants_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет, Спасибо.
        /// </summary>
        public static string NoButton_NoThanks {
            get {
                return ResourceManager.GetString("NoButton_NoThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неа.
        /// </summary>
        public static string NoButton_NotReally {
            get {
                return ResourceManager.GetString("NoButton_NotReally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам нравится GitTrends?.
        /// </summary>
        public static string TitleLabel_EnjoyingGitTrends {
            get {
                return ResourceManager.GetString("TitleLabel_EnjoyingGitTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам нравится Новая Версия GitTrends?.
        /// </summary>
        public static string TitleLabel_EnjoyingNewVersionOfGitTrends {
            get {
                return ResourceManager.GetString("TitleLabel_EnjoyingNewVersionOfGitTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотите оставить ревью?.
        /// </summary>
        public static string TitleLabel_Feedback {
            get {
                return ResourceManager.GetString("TitleLabel_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да, Конечно!.
        /// </summary>
        public static string YesButton_OkSure {
            get {
                return ResourceManager.GetString("YesButton_OkSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да!.
        /// </summary>
        public static string YesButton_Yes {
            get {
                return ResourceManager.GetString("YesButton_Yes", resourceCulture);
            }
        }
    }
}
