//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SplashScreenPageConstants {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SplashScreenPageConstants() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.SplashScreenPageConstants", typeof(SplashScreenPageConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        public static string ConnectingToServers {
            get {
                return ResourceManager.GetString("ConnectingToServers", resourceCulture);
            }
        }
        
        public static string StillWorkingOnIt {
            get {
                return ResourceManager.GetString("StillWorkingOnIt", resourceCulture);
            }
        }
        
        public static string LetsTryItLikeThis {
            get {
                return ResourceManager.GetString("LetsTryItLikeThis", resourceCulture);
            }
        }
        
        public static string MaybeThis {
            get {
                return ResourceManager.GetString("MaybeThis", resourceCulture);
            }
        }
        
        public static string AnotherTry {
            get {
                return ResourceManager.GetString("AnotherTry", resourceCulture);
            }
        }
        
        public static string ItShouldntTakeThisLong {
            get {
                return ResourceManager.GetString("ItShouldntTakeThisLong", resourceCulture);
            }
        }
        
        public static string AreYouSureInternetConnectionIsGood {
            get {
                return ResourceManager.GetString("AreYouSureInternetConnectionIsGood", resourceCulture);
            }
        }
        
        public static string PreviewMode {
            get {
                return ResourceManager.GetString("PreviewMode", resourceCulture);
            }
        }
        
        public static string WarningsMayAppear {
            get {
                return ResourceManager.GetString("WarningsMayAppear", resourceCulture);
            }
        }
        
        public static string InitializationFailed {
            get {
                return ResourceManager.GetString("InitializationFailed", resourceCulture);
            }
        }
        
        public static string EnsureInternetConnectionAndLatestVersion {
            get {
                return ResourceManager.GetString("EnsureInternetConnectionAndLatestVersion", resourceCulture);
            }
        }
    }
}
