//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitTrends.Mobile.Common.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SplashScreenPageConstants_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SplashScreenPageConstants_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitTrends.Mobile.Common.Constants.SplashScreenPageConstants-ru", typeof(SplashScreenPageConstants_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще одна попытка.
        /// </summary>
        public static string AnotherTry {
            get {
                return ResourceManager.GetString("AnotherTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что Интернет подключение хорошее?.
        /// </summary>
        public static string AreYouSureInternetConnectionIsGood {
            get {
                return ResourceManager.GetString("AreYouSureInternetConnectionIsGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение к серверу.
        /// </summary>
        public static string ConnectingToServers {
            get {
                return ResourceManager.GetString("ConnectingToServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убедитесь, что Интернет Поключение Доступно и Обновите GitTrends до Последней Версии.
        /// </summary>
        public static string EnsureInternetConnectionAndLatestVersion {
            get {
                return ResourceManager.GetString("EnsureInternetConnectionAndLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация не удалась.
        /// </summary>
        public static string InitializationFailed {
            get {
                return ResourceManager.GetString("InitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация.
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хмммм, это не должер занимать так много времени.
        /// </summary>
        public static string ItShouldntTakeThisLong {
            get {
                return ResourceManager.GetString("ItShouldntTakeThisLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давайте попробуем это так.
        /// </summary>
        public static string LetsTryItLikeThis {
            get {
                return ResourceManager.GetString("LetsTryItLikeThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Может быть это.
        /// </summary>
        public static string MaybeThis {
            get {
                return ResourceManager.GetString("MaybeThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим Предпросмотра.
        /// </summary>
        public static string PreviewMode {
            get {
                return ResourceManager.GetString("PreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В процессе работы.
        /// </summary>
        public static string StillWorkingOnIt {
            get {
                return ResourceManager.GetString("StillWorkingOnIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Могут появиться некоторые предупреждения связаные с лицензией.
        /// </summary>
        public static string WarningsMayAppear {
            get {
                return ResourceManager.GetString("WarningsMayAppear", resourceCulture);
            }
        }
    }
}
